/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Website } from "./Website";
import { WebsiteCountArgs } from "./WebsiteCountArgs";
import { WebsiteFindManyArgs } from "./WebsiteFindManyArgs";
import { WebsiteFindUniqueArgs } from "./WebsiteFindUniqueArgs";
import { CreateWebsiteArgs } from "./CreateWebsiteArgs";
import { UpdateWebsiteArgs } from "./UpdateWebsiteArgs";
import { DeleteWebsiteArgs } from "./DeleteWebsiteArgs";
import { WebsiteSubmitInput } from "../WebsiteSubmitInput";
import { AnalysisResultOutput } from "../../analysisResult/AnalysisResultOutput";
import { WebsiteService } from "../website.service";
@graphql.Resolver(() => Website)
export class WebsiteResolverBase {
  constructor(protected readonly service: WebsiteService) {}

  async _websitesMeta(
    @graphql.Args() args: WebsiteCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Website])
  async websites(
    @graphql.Args() args: WebsiteFindManyArgs
  ): Promise<Website[]> {
    return this.service.websites(args);
  }

  @graphql.Query(() => Website, { nullable: true })
  async website(
    @graphql.Args() args: WebsiteFindUniqueArgs
  ): Promise<Website | null> {
    const result = await this.service.website(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Website)
  async createWebsite(
    @graphql.Args() args: CreateWebsiteArgs
  ): Promise<Website> {
    return await this.service.createWebsite({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => Website)
  async updateWebsite(
    @graphql.Args() args: UpdateWebsiteArgs
  ): Promise<Website | null> {
    try {
      return await this.service.updateWebsite({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Website)
  async deleteWebsite(
    @graphql.Args() args: DeleteWebsiteArgs
  ): Promise<Website | null> {
    try {
      return await this.service.deleteWebsite(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Query(() => String)
  async SubmitWebsite(
    @graphql.Args()
    args: string
  ): Promise<string> {
    return this.service.SubmitWebsite(args);
  }

  @graphql.Mutation(() => AnalysisResultOutput)
  async SubmitWebsiteForAnalysis(
    @graphql.Args()
    args: WebsiteSubmitInput
  ): Promise<AnalysisResultOutput> {
    return this.service.SubmitWebsiteForAnalysis(args);
  }
}
